### ISSUE TITLE
react-native-flipper-performance-plugin cannot be used with expo-community-flipper

### ISSUE THREAD

**Issue by erisvaldojunior** [jakobo/expo-community-flipper#13]
After installing react-native-flipper-performance-plugin as a devDependency, all my EAS iOS Productions builds are failing.

Command: eas build -p ios --proflie production

```
Log:

Compiling react-native-flipper-performance-plugin Pods/react-native-flipper-performance-plugin » FlipperPerformancePlugin.m

❌  (node_modules/react-native-flipper-performance-plugin/ios/FlipperPerformancePlugin.h:3:9)

  1 | #import <Foundation/Foundation.h>
  2 | 
> 3 | #import <FlipperKit/FlipperPlugin.h>
    |         ^ 'FlipperKit/FlipperPlugin.h' file not found
  4 | #import <React/RCTBridge.h>
  5 | 
  6 | @interface FlipperPerformancePlugin : NSObject<RCTBridgeModule, FlipperPlugin>
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'sovran-react-native' from project 'Pods')
▸ 	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Curebase-hlhkbcpnqfhmkyadpnbibuogbjfb/Build/Intermediates.noindex/ArchiveIntermediates/Curebase/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-flipper-performance-plugin.build/Objects-normal/arm64/FlipperPerformancePlugin.o /Users/expo/workingdir/build/node_modules/react-native-flipper-performance-plugin/ios/FlipperPerformancePlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-flipper-performance-plugin' from project 'Pods')
▸ (2 failures)
20
```

I do have FLIPPER_DISABLE on my eas.json:

```
    "production": {
      "env": {
        "APP_ENVIRONMENT": "production",
        "FLIPPER_DISABLE": "1"
      }
    }

```

Removing FLIPPER_DISABLE made it work. Any thoughts?

**Comment by thecodedrift** [comment]
Thanks for reporting, was on a vacation the past few weeks. I'll dig into it. Can you share your EAS & Expo SDK versions?

**Comment by thecodedrift** [comment]
Alright, so I dug into the rnfpp's code. Here's what's going on.

1. The `FLIPPER_DISABLE` flag exists because **all** eas builds have the `CI` value set. This means we cannot use react native's original `if !ENV['CI']` line for enabling/disabling flipper support; doing so means the custom dev clients would never have flipper.
2. Autolinking automatically includes [react-native-performance](https://github.com/oblador/react-native-performance/tree/master/packages/react-native-performance) in the podfile. Unfortunately, it's [podspec](https://github.com/oblador/react-native-performance/blob/master/packages/react-native-performance/react-native-performance.podspec) currently assumes flipper is there and available

Unfortunately, this isn't fixable in the config plugin. If react-native-flipper-performance-plugin is installed, you must also not include the `FLIPPER_DISABLE` flag. If you install both expo-community-flipper and react-native-flipper-performance-plugin as dev dependencies, then their availability will be linked.

Alternatively, I'd suggest opening an issue on `react-native-flipper-performance-plugin` referencing this thread and ask if the library can include an ENV flag to enable/disable the pod at build time for granular control.

**Comment by thecodedrift** [comment]
Closing, as this is something that's out of our hands. Unfortunately, if using a react native flipper plugin that either (1) has no `ENV` checks for disabling during autolinking or (2) relies on the `ENV['CI']` to toggle its availability, it cannot work in an expo + eas environment due to expo's `CI=1` flag being always set.

See: https://github.com/jakobo/expo-community-flipper/issues/9

**Comment by thecodedrift** [comment]
To disable react-native-flipper-performance-plugin when the `FLIPPER_DISABLE` flag is set:

1. create a `react-native.config.js` file in your project root.
2. Add a line that disables autolinking for rnfp if the flipper disable flag is set

```js
module.exports = {
  dependencies: {
    ...(process.env.FLIPPER_DISABLE === "1" ? {} : {
      "react-native-flipper-performance-plugin": {
        platforms: {
          android: null,
          ios: null
        },
      },
    })
  },
};
```

This is based on the suggestion of oblador in the rnfp repo.
