### ISSUE TITLE
Question: can I use this with a non-simulator?

### ISSUE THREAD

**Issue by nandorojo** [jakobo/expo-community-flipper#14]
Any idea if I can use Flipper with the dev client on my physical iPhone device?

Thanks for the plugin btw!

**Comment by thecodedrift** [comment]
Yep. Works with iOS as long as you build the custom dev client and provision the device like normal.

(And likewise, thank you for Moti & Dripsy 😍 )

**Comment by nandorojo** [comment]
interesting, it doesn’t seem to show on flipper from my device! i’ll try again soon

**Comment by thecodedrift** [comment]
I'll keep this open while we're digging into it. If you get a chance to run a prebuild, can you share the generated `Podfile`? It's helpful to make sure Flipper's pod is being included correctly, since it must still rely on expo's regex style insertions.

**Comment by nandorojo** [comment]
it works on the simulator, just not when the dev client runs on the device. i’ll try it again at my laptop and let you know

**Comment by thecodedrift** [comment]
Discussed offline with nandorojo and did some research into the cause and we have a workaround. 🎉 

Relevant upstream ticket: https://github.com/expo/expo/issues/17495. Until fixed, you can work around this issue by using the classic manifest instead of the expo updates variant using the following command:

`expo start --dev-client --force-manifest-type=classic`

**Tradeoffs**
When using classic manifest, you cannot test changes related to expo-updates such as checking for new updates. This workaround is not suitable for adhoc and testflight builds (though these shouldn't be using flipper anyway).
