### ISSUE TITLE
Discussion: Use js-flipper instead?

### ISSUE THREAD

**Issue by usrbowe** [jakobo/expo-community-flipper#48]
I would like to open this for discussion to use just JS connection [js-flipper](https://www.npmjs.com/package/js-flipper), which provide same functionality for RN/Expo apps and does not require to hassle with native dependency and also makes connecting to all devices easier (does not require adb/idb).

I could provide a demo example and describe this approach in more details if found like a interesting option for Expo x Flipper use case.

**Comment by thecodedrift** [comment]
Hi @usrbowe, thanks for sharing the link. The js-flipper package is from the same makers as react-native-flipper, but designed specifically for a browser and node.js environment: https://fbflipper.com/docs/getting-started/javascript/ The metro bundler is... kinda a node environment, but not completely as a large amount of code runs on-device and some of it in native-space such as Swift or Kotlin.

Because of this, we still need the native bindings provided by RSpec/Folly/etc. Otherwise developers would lose access to the debugger, layout information, performance and memory monitoring, and dumps from crashes. These aren't things metro can't really catch, so a special on-device library is critical. It's my hope that as flipper continues to stabilize, Facebook will roll out a plugin registration library that just has a peer-dependency on a react-native-flipper version. This would let people add plugins like the redux plugin without going through the hassle of native dependencies.

All that said, if you want to put together a Snak that shows the js-only flipper in action this could be great for people who don't need the native introspection!
