### ISSUE TITLE
Flipper SDK version

### ISSUE THREAD

**Issue by obasille** [jakobo/expo-community-flipper#6]
Hi,

I'm using Expo 44, expo-community-flipper 44.0.1, react-native-flipper 0.140 and am running the dev client in the Android simulator on Windows 10.

> expo run:android

The Flipper doc recommends to use the latest Flipper SDK which is 140 at the moment, but this creates compilation problems (because it requires Android SDK 31).

Some other version like 127 crashes the app.

The readme examples mention version 123 which is the version I ended up using.

If this the version you recommend using?

Thanks!

**Comment by thecodedrift** [comment]
I've verified with 123 in EAS so I know that combination works. I'm happy to add "known working combinations" to the README if we think it could help folks out. Unfortunately, Flipper is still a bit of a moving target since we're looking for a Flipper that works with SDKs (and Hermes versions) that are bundled in with Expo.

**Comment by thecodedrift** [comment]
Resolved in `44.0.2` https://github.com/jakobo/expo-community-flipper/blob/main/CHANGELOG.md#4402

**Comment by obasille** [comment]
Awesome, thanks!!

**Comment by obasille** [comment]
JFYI Flipper SDK was updated to 125 in RN 0.68 :)
https://reactnative.dev/blog/2022/03/30/version-068
