### ISSUE TITLE
How to disable Flipper in production

### ISSUE THREAD

**Issue by bpouzet** [jakobo/expo-community-flipper#9]
Hello,

It is possible to disable Flipper in production? Because on iOS there are a lot of imports

**Comment by thecodedrift** [comment]
Totally understand.

The [flipper docs](https://fbflipper.com/docs/troubleshooting/#disable-flipper-on-ci-builds-ios) mention adding a `!ENV['CI']` check for disabling the build in CI which won't work for us, since many devs use EAS to make a new development client. However, there's no reason we can't use a different ENV value to disable flipper in builds, for example `ENV['FLIPPER_DISABLE']`. This would be possible to add in a backward compatible way and can be toggled with expo/eas secrets.

Would that work for your use case?

**Comment by bpouzet** [comment]
Hello @jakobo, it sounds great. Thank you!

**Comment by thecodedrift** [comment]
Fixed in `45.1.0`  with the new `FLIPPER_DISABLE` env flag.

**Comment by Noitidart** [comment]
Thank you! Is it possible to add this env var to my eas config? My current eas.json looks like this:

```
{
  "build": {
    "release": {
      "ios": {
        "image": "latest"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  },
  "cli": {
    "version": ">= 0.38.2",
    "requireCommit": true
  }
}
```

And my app.json expo part looks like this:

```
{
  "expo": {
    "..."
    "plugins": [
      ["expo-community-flipper"],
      ["react-native-flipper-performance-plugin"]
    ]
  }
}
```

**Comment by thecodedrift** [comment]
@Noitidart Yes, you can include env values either at the EAS service level or in your eas.json: https://docs.expo.dev/build-reference/variables/

```json
{
  "build": {
    "...": "...",
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": {
        "env-key": "env-value"
      }
    }
  }
}
```

**Comment by Noitidart** [comment]
Oh thanks very much @jakobo !

**Comment by thecodedrift** [comment]
Credit where credit's due. @all-contributors, can you add @bpouzet for ideas

I don't think we'd have addressed the ENV issue w/o your help. ❤️
